version: '2'
services:
  db_camunda:
    image: postgres:12-alpine
    container_name: postgres-camunda
    restart: always
    env_file: ".env"
    environment:
      POSTGRES_DB: $BPM_DB_NAME
      POSTGRES_USER: $BPM_DB_USER
      POSTGRES_PASSWORD: $BPM_DB_PASSWORD
    volumes:
      - ./data/camunda/postgresql:/var/lib/postgresql/data
    networks:
      - postgres-camunda
  db_homs:
    image: postgres:12-alpine
    container_name: postgres-homs
    restart: always
    env_file: ".env"
    environment:
      POSTGRES_DB: $HOMS_DB_NAME
      POSTGRES_USER: $HOMS_DB_USER
      POSTGRES_PASSWORD: $HOMS_DB_PASSWORD
    volumes:
      - ./data/homs/postgresql:/var/lib/postgresql/data
    networks:
      - postgres-homs
  minio:
    image: minio/minio:RELEASE.2021-06-17T00-10-46Z
    container_name: minio
    restart: always
    command: server /opt/minio --address "0.0.0.0:9001"
    env_file: ".env"
    environment:
      - TZ=${TZ}
    volumes:
      - ./data/minio:/var/minio
    ports:
      - $MINIO_PORT:9001
    networks:
      - default
      - minio
  homs:
    image: latera/homs:2.7.0
    container_name: homs
    restart: always
    env_file: ".env"
    environment:
      - TZ=${TZ}
      - RAILS_ENV=production
      - SEED_DB=${HOMS_DB_SEED}
      - LOG_LEVEL=${HOMS_LOG_LEVEL}
      - ADMIN_EMAIL=${HOMS_USER}
      - ADMIN_PASSWORD=${HOMS_PASSWORD}
      - ADMIN_API_TOKEN=${HOMS_TOKEN}
      - REDIS_URL=redis://redis
    depends_on:
      - db_homs
    volumes:
      - ./seeds.rb:/opt/homs/db/seeds.rb
      - ./hbw.yml:/opt/homs/config/hbw.yml
      - ./demo_processes/locales:/opt/homs/config/locales/bp:ro
    ports:
      - $HOMS_PORT:3000
    networks:
      - default
      - postgres-homs
      - camunda
      - homs
      - redis
      - minio
  camunda:
    image: latera/camunda-ext-2-lite:6.0
    container_name: camunda
    restart: always
    env_file: ".env"
    environment:
      DB_USERNAME: $BPM_DB_USER
      DB_PASSWORD: $BPM_DB_PASSWORD
      LOG_LVL: "info"
      WAIT_FOR: "${BPM_DB_HOST}:${BPM_DB_PORT}"
      WAIT_FOR_TIMEOUT: 120
    ports:
      - $BPM_PORT:8080
    depends_on:
      - db_camunda
    networks:
      - default
      - postgres-camunda
      - homs
      - minio
  redis:
    image: healthcheck/redis
    container_name: redis
    restart: always
    environment:
      - TZ=${TZ}
    networks:
      - redis
networks:
  postgres-camunda:
    internal: true
    name: postgres-camunda
  postgres-homs:
    internal: true
    name: postgres-homs
  camunda:
    internal: true
    name: camunda
  homs:
    internal: true
    name: homs
  minio:
    internal: true
    name: minio
  redis:
    internal: true
    name: redis
